Fix/making items accessible
Shemnei/json-resume pull request #1
Opened 2023-08-15 07:28 UTC by niko-dunixi

I'm not sure how this was _intended_ to be used, but I was using this library to serialize my resume into memory to convert it into other formats and markups, but I couldn't figure out how to pull the original string values out of the `Keyword` and `Highlight`.

I found that a simple way to do this was by implementing the `Display` trait, which gets `ToString` for free (per the [docs](https://doc.rust-lang.org/std/string/trait.ToString.html) recommendation).

What context is this library normally being used for? Is there a better way to do this that would be more homogenous with your intentions and plans?

2023-08-25 18:25 UTC, Shemnei requested changes
Hey sorry for the very late response and thank you for the pr.
I would like to keep your display impls but would suggest to make the inner types just `pub` as the "offical" way to access the strings.

2023-08-25 18:25 UTC, Shemnei commented on src/lib.rs
>  pub struct Highlight(String);
```suggestion
pub struct Highlight(pub String);
```

2023-08-25 18:25 UTC, Shemnei commented on src/lib.rs
>  pub struct Keyword(String);
```suggestion
pub struct Keyword(pub String);
```

2023-08-25 18:32 UTC, Shemnei commented
Ahh an btw the crate is currently still in a "rought"/draft state so you might want to switch. But i would also be happy to support you if you decide to stick with it 😄

2023-08-29 04:39 UTC, niko-dunixi commented
@Shemnei How's that looking? I made the items public, but I took a second glance over and found the other Unit-Structs and did the same for all of them. And no worries as far as rough state goes, this is actually near-perfect for me. I needed the type-definition and yours fit the bill almost to a T, so I'm probably gunna stick with your crate for a while :)

2023-08-29 13:58 UTC, Shemnei commented
@niko-dunixi thanks so much, really appreciate it :100:

2023-08-29 13:58 UTC, Shemnei approved these changes

2023-08-29 14:36 UTC, merged

2023-08-29 17:30 UTC, niko-dunixi commented
Rock and roll! Thanks @Shemnei !